# test pyFM

In [28]:
from pyfm import pylibfm
from sklearn.feature_extraction import DictVectorizer
import numpy as np
train = [
{"user": "1", "item": "5", "age": 19},
{"user": "2", "item": "43", "age": 33},
{"user": "3", "item": "20", "age": 55},
{"user": "4", "item": "10", "age": 20},
]
v = DictVectorizer()
X = v.fit_transform(train)
print(X.toarray())
y = np.repeat(1.0,X.shape[0])
fm = pylibfm.FM()
fm.fit(sa,y)
fm.predict(v.transform({"user": "1", "item": "10", "age": 24}))

[[19.  0.  0.  0.  1.  1.  0.  0.  0.]
 [33.  0.  0.  1.  0.  0.  1.  0.  0.]
 [55.  0.  1.  0.  0.  0.  0.  1.  0.]
 [20.  1.  0.  0.  0.  0.  0.  0.  1.]]
Creating validation dataset of 0.01 of training for adaptive regularization
-- Epoch 1
Training log loss: 0.68820


array([0.698862])

In [9]:
y

array([1., 1., 1., 1.])

In [21]:
X

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [5]:
X.toarray()

array([[19.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [33.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
       [55.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [20.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [25]:
from scipy import sparse
A = np.array([[1.0,2.0,0.],[0,0,3.0],[1.0,0,4.0],[0,3.1,3.1]])

A

array([[1. , 2. , 0. ],
       [0. , 0. , 3. ],
       [1. , 0. , 4. ],
       [0. , 3.1, 3.1]])

In [26]:
sa=sparse.csr_matrix(A)   # Here's the initialization of the sparse matrix.

In [27]:
sa.toarray()

array([[1. , 2. , 0. ],
       [0. , 0. , 3. ],
       [1. , 0. , 4. ],
       [0. , 3.1, 3.1]])